# Local officer face database configuration.

# Files and folders.
OFFICER_DATABASE_CSV = "database/officers.csv"
OFFICER_IMAGES_DIR = "database/officers"
ALERTS_DIR = "alerts"

# Webcam and recognition.
CAMERA_INDEX = 0
CAMERA_BACKEND = "V4L2"
CAMERA_FOURCC = "MJPG"
CAMERA_FPS = 30
CAMERA_FRAME_WIDTH = 960
CAMERA_FRAME_HEIGHT = 540
RECOGNITION_TOLERANCE = 0.58
RESIZE_FACTOR = 0.4
FACE_DETECTION_UPSAMPLE = 1
FACE_DETECTION_MODEL = "hog"
PROCESS_EVERY_N_FRAMES = 2

# Labels shown in the camera window.
OFFICER_LABEL = "Officer"
UNKNOWN_LABEL = "Possible Trespassing Civilian"
ALERT_BANNER_TEXT = "ALERT: UNKNOWN PERSON DETECTED"

# Alert behavior.
UNKNOWN_ALERT_COOLDOWN_SECONDS = 8
SAVE_UNKNOWN_SNAPSHOTS = True
ENABLE_TERMINAL_BELL = True
AUTO_CLEAN_INVALID_SAMPLES = True

# Enrollment capture.
ENROLLMENT_POSES = ["CENTER", "LEFT", "RIGHT", "UP", "DOWN"]
ENROLLMENT_IMAGES_PER_POSE = 4
ENROLLMENT_FRAME_SKIP = 4
ENROLLMENT_COUNTDOWN_SECONDS = 2
ENROLLMENT_POSE_HOLD_FRAMES = 6
ENROLLMENT_CAPTURE_GAP_FRAMES = 3
ENROLLMENT_CENTER_YAW_THRESHOLD = 0.30
ENROLLMENT_SIDE_YAW_THRESHOLD = 0.11
ENROLLMENT_UP_PITCH_THRESHOLD = 0.40
ENROLLMENT_DOWN_PITCH_THRESHOLD = 0.49

# Weapon detection can be added later after face recognition is stable.
